apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-app
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-app
  template:
    metadata:
      labels:
        app: ostad-app
    spec:
      containers:
        - name: ostad-container
          image: rabbi728/ostadassignmant:latest
          ports:
            - containerPort: 8000
