apiVersion: v1
kind: Service
metadata:
  name: ostadassignmant-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: ostadassignmant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
